name: Build
env:
  FLUTTER_VERSION: "2.16.1"
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ubuntu
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter --version
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
